In [103]:
import numpy as np

In [104]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [105]:
x = np.array([2,3,5,1,2,4])
print(x)
print('total elements =>', x.size)
print('dimension wise elements =>', x.shape)
print('dimension count=>', x.ndim)


[2 3 5 1 2 4]
total elements => 6
dimension wise elements => (6,)
dimension count=> 1


In [106]:
y = np.array([[2,3,5], [1,2,4]])
print(y)
print('total elements =>', y.size)
print('dimension wise elements =>', y.shape)
print('dimension count=>', y.ndim)

[[2 3 5]
 [1 2 4]]
total elements => 6
dimension wise elements => (2, 3)
dimension count=> 2


In [107]:
z = np.array([[2,3,5], [1,2,4], [1,2,3]])
print(z)
print('total elements =>', z.size)
print('dimension wise elements =>', z.shape)
print('dimension count=>', z.ndim)

[[2 3 5]
 [1 2 4]
 [1 2 3]]
total elements => 9
dimension wise elements => (3, 3)
dimension count=> 2


In [108]:
p = [1,2,3,4,5,6,7,8,9,10]
t = np.array([p,p,p,p,p,p,p,p,p,p])
print(t)
print('total elements =>', t.size)
print('dimension wise elements =>', t.shape)
print('dimension count=>', t.ndim)

[[ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]]
total elements => 100
dimension wise elements => (10, 10)
dimension count=> 2


In [109]:
d = np.arange(-10,11,.5)
d. shape

(42,)

In [110]:
d.reshape(6,7)

array([[-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ],
       [ -6.5,  -6. ,  -5.5,  -5. ,  -4.5,  -4. ,  -3.5],
       [ -3. ,  -2.5,  -2. ,  -1.5,  -1. ,  -0.5,   0. ],
       [  0.5,   1. ,   1.5,   2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ],
       [  7.5,   8. ,   8.5,   9. ,   9.5,  10. ,  10.5]])

In [111]:
d.reshape(2,3,7)

array([[[-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ],
        [ -6.5,  -6. ,  -5.5,  -5. ,  -4.5,  -4. ,  -3.5],
        [ -3. ,  -2.5,  -2. ,  -1.5,  -1. ,  -0.5,   0. ]],

       [[  0.5,   1. ,   1.5,   2. ,   2.5,   3. ,   3.5],
        [  4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ],
        [  7.5,   8. ,   8.5,   9. ,   9.5,  10. ,  10.5]]])

In [112]:
a = np.linspace(1,1001,10)
a

array([1.00000000e+00, 1.12111111e+02, 2.23222222e+02, 3.34333333e+02,
       4.45444444e+02, 5.56555556e+02, 6.67666667e+02, 7.78777778e+02,
       8.89888889e+02, 1.00100000e+03])

In [1]:
d = np.random.randint(1,4,(10,10))

NameError: name 'np' is not defined

In [114]:
print(d)

[[2 3 2 1 3 3 3 1 3 3]
 [3 1 1 3 1 1 2 1 1 1]
 [3 3 1 3 3 2 2 3 3 2]
 [2 2 3 1 3 1 2 1 2 1]
 [2 1 1 3 1 3 1 1 1 2]
 [3 3 2 1 2 1 1 3 1 1]
 [2 1 1 2 1 1 2 1 2 1]
 [2 1 2 1 2 1 3 3 3 1]
 [3 3 1 2 1 2 3 1 3 2]
 [2 1 3 1 1 2 1 2 2 2]]


In [115]:
d[-1]

array([2, 1, 3, 1, 1, 2, 1, 2, 2, 2])

In [116]:
d[3,5]   # d[0][0]

1

In [117]:
d[4,4]

1

In [118]:
d[:, -3]

array([1, 1, 3, 1, 1, 3, 1, 3, 1, 2])

In [119]:
d[:5, 2]   # first five rows of column idx 2

array([2, 1, 1, 3, 1])

In [120]:
d[5:,]     # last five rows of column idx 2

array([[3, 3, 2, 1, 2, 1, 1, 3, 1, 1],
       [2, 1, 1, 2, 1, 1, 2, 1, 2, 1],
       [2, 1, 2, 1, 2, 1, 3, 3, 3, 1],
       [3, 3, 1, 2, 1, 2, 3, 1, 3, 2],
       [2, 1, 3, 1, 1, 2, 1, 2, 2, 2]])

In [121]:
d[5:, 2] # last five rows of column idx 2

array([2, 1, 2, 1, 3])

In [122]:
d[:5, :5]

array([[2, 3, 2, 1, 3],
       [3, 1, 1, 3, 1],
       [3, 3, 1, 3, 3],
       [2, 2, 3, 1, 3],
       [2, 1, 1, 3, 1]])

In [123]:
x = np.random.randint(1,10, (3,3))
y = np.random.randint(1,10, (3,3))
print(x,'\n', y)

[[1 8 2]
 [8 4 2]
 [7 4 1]] 
 [[5 3 2]
 [3 4 7]
 [8 2 8]]


In [124]:
x+y

array([[ 6, 11,  4],
       [11,  8,  9],
       [15,  6,  9]])

In [125]:
x-y

array([[-4,  5,  0],
       [ 5,  0, -5],
       [-1,  2, -7]])

In [126]:
x*y

array([[ 5, 24,  4],
       [24, 16, 14],
       [56,  8,  8]])

In [127]:
x/y

array([[0.2       , 2.66666667, 1.        ],
       [2.66666667, 1.        , 0.28571429],
       [0.875     , 2.        , 0.125     ]])

In [128]:
x + 10

array([[11, 18, 12],
       [18, 14, 12],
       [17, 14, 11]])

In [129]:
x - 10

array([[-9, -2, -8],
       [-2, -6, -8],
       [-3, -6, -9]])

In [130]:
x * 10

array([[10, 80, 20],
       [80, 40, 20],
       [70, 40, 10]])

In [131]:
np.matmul(x,y)

array([[45, 39, 74],
       [68, 44, 60],
       [55, 39, 50]])

In [132]:
np.multiply(x,y)

array([[ 5, 24,  4],
       [24, 16, 14],
       [56,  8,  8]])

In [133]:
x * y

array([[ 5, 24,  4],
       [24, 16, 14],
       [56,  8,  8]])

In [134]:
np.cross(x,y)

array([[ 10,   8, -37],
       [ 20, -50,  20],
       [ 30, -48, -18]])

In [135]:
np.hstack([x,y])

array([[1, 8, 2, 5, 3, 2],
       [8, 4, 2, 3, 4, 7],
       [7, 4, 1, 8, 2, 8]])

In [136]:
np.vstack([x,y])

array([[1, 8, 2],
       [8, 4, 2],
       [7, 4, 1],
       [5, 3, 2],
       [3, 4, 7],
       [8, 2, 8]])

In [137]:
np.append(x,y, axis = 0)  # axis 0 is for row wise and  1 for column

array([[1, 8, 2],
       [8, 4, 2],
       [7, 4, 1],
       [5, 3, 2],
       [3, 4, 7],
       [8, 2, 8]])

In [138]:
x.max()

8

In [139]:
x.max(axis = 0)

array([8, 8, 2])

In [140]:
x.min(axis = 1)

array([1, 2, 1])

In [141]:
x.flatten()

array([1, 8, 2, 8, 4, 2, 7, 4, 1])

In [144]:
d[d > 2]   # boolean filter

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3])

In [143]:
d[d == 1]     # give all the ones

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])