In [2]:
import numpy as np

In [3]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [4]:
x = np.array([2,3,5,1,2,4])
print(x)
print('total elements =>', x.size)
print('dimension wise elements =>', x.shape)
print('dimension count=>', x.ndim)

[2 3 5 1 2 4]
total elements => 6
dimension wise elements => (6,)
dimension count=> 1


In [5]:
y = np.array([[2,3,5], [1,2,4]])
print(y)
print('total elements =>', y.size)
print('dimension wise elements =>', y.shape)
print('dimension count=>', y.ndim)

[[2 3 5]
 [1 2 4]]
total elements => 6
dimension wise elements => (2, 3)
dimension count=> 2


In [6]:
z = np.array([[2,3,5], [1,2,4], [1,2,3]])
print(z)
print('total elements =>', z.size)
print('dimension wise elements =>', z.shape)
print('dimension count=>', z.ndim)

[[2 3 5]
 [1 2 4]
 [1 2 3]]
total elements => 9
dimension wise elements => (3, 3)
dimension count=> 2


In [7]:
p = [1,2,3,4,5,6,7,8,9,10]
t = np.array([p,p,p,p,p,p,p,p,p,p])
print(t)
print('total elements =>', t.size)
print('dimension wise elements =>', t.shape)
print('dimension count=>', t.ndim)

[[ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]]
total elements => 100
dimension wise elements => (10, 10)
dimension count=> 2


In [8]:
d = np.arange(-10,11,.5)
d. shape

(42,)

In [9]:
d.reshape(6,7)

array([[-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ],
       [ -6.5,  -6. ,  -5.5,  -5. ,  -4.5,  -4. ,  -3.5],
       [ -3. ,  -2.5,  -2. ,  -1.5,  -1. ,  -0.5,   0. ],
       [  0.5,   1. ,   1.5,   2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ],
       [  7.5,   8. ,   8.5,   9. ,   9.5,  10. ,  10.5]])

In [10]:
d.reshape(2,3,7)

array([[[-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ],
        [ -6.5,  -6. ,  -5.5,  -5. ,  -4.5,  -4. ,  -3.5],
        [ -3. ,  -2.5,  -2. ,  -1.5,  -1. ,  -0.5,   0. ]],

       [[  0.5,   1. ,   1.5,   2. ,   2.5,   3. ,   3.5],
        [  4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ],
        [  7.5,   8. ,   8.5,   9. ,   9.5,  10. ,  10.5]]])

In [11]:
a = np.linspace(1,1001,10)
a

array([1.00000000e+00, 1.12111111e+02, 2.23222222e+02, 3.34333333e+02,
       4.45444444e+02, 5.56555556e+02, 6.67666667e+02, 7.78777778e+02,
       8.89888889e+02, 1.00100000e+03])

In [12]:
d = np.random.randint(1,4,(10,10))
d

array([[2, 2, 2, 2, 2, 2, 3, 1, 1, 1],
       [3, 2, 3, 3, 3, 1, 2, 1, 2, 2],
       [1, 2, 3, 3, 3, 2, 1, 2, 2, 3],
       [2, 1, 3, 1, 2, 3, 1, 1, 2, 1],
       [1, 3, 3, 2, 3, 3, 3, 2, 1, 3],
       [1, 3, 1, 1, 1, 2, 1, 3, 1, 2],
       [1, 1, 2, 1, 1, 2, 1, 2, 2, 3],
       [1, 1, 2, 1, 3, 3, 3, 1, 3, 2],
       [1, 2, 3, 3, 2, 1, 2, 1, 2, 2],
       [3, 2, 1, 2, 3, 2, 3, 2, 1, 1]])

In [13]:
print(d)

[[2 2 2 2 2 2 3 1 1 1]
 [3 2 3 3 3 1 2 1 2 2]
 [1 2 3 3 3 2 1 2 2 3]
 [2 1 3 1 2 3 1 1 2 1]
 [1 3 3 2 3 3 3 2 1 3]
 [1 3 1 1 1 2 1 3 1 2]
 [1 1 2 1 1 2 1 2 2 3]
 [1 1 2 1 3 3 3 1 3 2]
 [1 2 3 3 2 1 2 1 2 2]
 [3 2 1 2 3 2 3 2 1 1]]


In [14]:
d[-1]

array([3, 2, 1, 2, 3, 2, 3, 2, 1, 1])

In [15]:
d[3,5]   # d[0][0]

3

In [16]:
d[4,4]

3

In [17]:
d[:, -3]

array([1, 1, 2, 1, 2, 3, 2, 1, 1, 2])

In [18]:
d[:5, 2]   # first five rows of column idx 2

array([2, 3, 3, 3, 3])

In [19]:
d[5:, 2] # last five rows of column idx 2

array([1, 2, 2, 3, 1])

In [20]:
d[:5, :5]

array([[2, 2, 2, 2, 2],
       [3, 2, 3, 3, 3],
       [1, 2, 3, 3, 3],
       [2, 1, 3, 1, 2],
       [1, 3, 3, 2, 3]])

In [21]:
x = np.random.randint(1,10, (3,3))
y = np.random.randint(1,10, (3,3))
print(x,'\n', y)

[[9 7 5]
 [2 1 1]
 [2 8 2]] 
 [[8 2 5]
 [9 1 7]
 [2 4 6]]


In [22]:
x+y

array([[17,  9, 10],
       [11,  2,  8],
       [ 4, 12,  8]])

In [23]:
x-y

array([[ 1,  5,  0],
       [-7,  0, -6],
       [ 0,  4, -4]])

In [24]:
x*y

array([[72, 14, 25],
       [18,  1,  7],
       [ 4, 32, 12]])

In [25]:
x/y

array([[1.125     , 3.5       , 1.        ],
       [0.22222222, 1.        , 0.14285714],
       [1.        , 2.        , 0.33333333]])

In [26]:
x + 10

array([[19, 17, 15],
       [12, 11, 11],
       [12, 18, 12]])

In [27]:
x - 10

array([[-1, -3, -5],
       [-8, -9, -9],
       [-8, -2, -8]])

In [28]:
x * 10

array([[90, 70, 50],
       [20, 10, 10],
       [20, 80, 20]])

In [29]:
np.matmul(x,y)

array([[145,  45, 124],
       [ 27,   9,  23],
       [ 92,  20,  78]])

In [30]:
x * y

array([[72, 14, 25],
       [18,  1,  7],
       [ 4, 32, 12]])

In [31]:
np.cross(x,y)

array([[ 25,  -5, -38],
       [  6,  -5,  -7],
       [ 40,  -8,  -8]])

In [32]:
np.hstack([x,y])

array([[9, 7, 5, 8, 2, 5],
       [2, 1, 1, 9, 1, 7],
       [2, 8, 2, 2, 4, 6]])

In [33]:
np.vstack([x,y])

array([[9, 7, 5],
       [2, 1, 1],
       [2, 8, 2],
       [8, 2, 5],
       [9, 1, 7],
       [2, 4, 6]])

In [34]:
np.append(x,y, axis = 0)  # axis 0 is for row wise and  1 for column

array([[9, 7, 5],
       [2, 1, 1],
       [2, 8, 2],
       [8, 2, 5],
       [9, 1, 7],
       [2, 4, 6]])

In [35]:
x.max()

9

In [36]:
x.max(axis = 0)

array([9, 8, 5])

In [37]:
x.min(axis = 1)

array([5, 1, 2])

In [38]:
x.flatten()

array([9, 7, 5, 2, 1, 1, 2, 8, 2])

In [39]:
d[d > 2]   # boolean filter

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3])

In [40]:
d[d == 1]     # give all the ones

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [44]:
a = [1,2,3,4]
b = np.array([a,a,a,a])
print(b)
print('total elements =>', b.size)
print('dimension wise elements =>', b.shape)
print('dimension count=>', b.ndim)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
total elements => 16
dimension wise elements => (4, 4)
dimension count=> 2
