In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
x = np.array([2,3,5,1,2,4])
print(x)
print('total elements =>', x.size)
print('dimension wise elements =>', x.shape)
print('dimension count=>', x.ndim)

[2 3 5 1 2 4]
total elements => 6
dimension wise elements => (6,)
dimension count=> 1


In [4]:
y = np.array([[2,3,5], [1,2,4]])
print(y)
print('total elements =>', y.size)
print('dimension wise elements =>', y.shape)
print('dimension count=>', y.ndim)

[[2 3 5]
 [1 2 4]]
total elements => 6
dimension wise elements => (2, 3)
dimension count=> 2


In [5]:
z = np.array([[2,3,5], [1,2,4], [1,2,3]])
print(z)
print('total elements =>', z.size)
print('dimension wise elements =>', z.shape)
print('dimension count=>', z.ndim)

[[2 3 5]
 [1 2 4]
 [1 2 3]]
total elements => 9
dimension wise elements => (3, 3)
dimension count=> 2


In [6]:
p = [1,2,3,4,5,6,7,8,9,10]
t = np.array([p,p,p,p,p,p,p,p,p,p])
print(t)
print('total elements =>', t.size)
print('dimension wise elements =>', t.shape)
print('dimension count=>', t.ndim)

[[ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]]
total elements => 100
dimension wise elements => (10, 10)
dimension count=> 2


In [7]:
d = np.arange(-10,11,.5)
d. shape

(42,)

In [8]:
d.reshape(6,7)

array([[-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ],
       [ -6.5,  -6. ,  -5.5,  -5. ,  -4.5,  -4. ,  -3.5],
       [ -3. ,  -2.5,  -2. ,  -1.5,  -1. ,  -0.5,   0. ],
       [  0.5,   1. ,   1.5,   2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ],
       [  7.5,   8. ,   8.5,   9. ,   9.5,  10. ,  10.5]])

In [9]:
d.reshape(2,3,7)

array([[[-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ],
        [ -6.5,  -6. ,  -5.5,  -5. ,  -4.5,  -4. ,  -3.5],
        [ -3. ,  -2.5,  -2. ,  -1.5,  -1. ,  -0.5,   0. ]],

       [[  0.5,   1. ,   1.5,   2. ,   2.5,   3. ,   3.5],
        [  4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ],
        [  7.5,   8. ,   8.5,   9. ,   9.5,  10. ,  10.5]]])

In [10]:
a = np.linspace(1,1001,10)
a

array([1.00000000e+00, 1.12111111e+02, 2.23222222e+02, 3.34333333e+02,
       4.45444444e+02, 5.56555556e+02, 6.67666667e+02, 7.78777778e+02,
       8.89888889e+02, 1.00100000e+03])

In [18]:
d = np.random.randint(1,4,(10,10))
d

array([[2, 1, 3, 3, 1, 2, 3, 1, 3, 1],
       [1, 2, 1, 2, 3, 3, 1, 1, 3, 3],
       [2, 3, 2, 3, 2, 2, 2, 1, 2, 1],
       [3, 2, 3, 1, 3, 2, 3, 3, 2, 3],
       [1, 3, 2, 1, 3, 3, 2, 3, 3, 2],
       [3, 3, 1, 3, 1, 3, 2, 1, 2, 3],
       [3, 1, 2, 1, 3, 2, 1, 1, 3, 2],
       [3, 2, 3, 3, 2, 1, 1, 1, 2, 3],
       [1, 1, 3, 2, 2, 3, 2, 2, 1, 2],
       [2, 1, 3, 3, 3, 3, 1, 1, 1, 3]])

In [19]:
print(d)

[[2 1 3 3 1 2 3 1 3 1]
 [1 2 1 2 3 3 1 1 3 3]
 [2 3 2 3 2 2 2 1 2 1]
 [3 2 3 1 3 2 3 3 2 3]
 [1 3 2 1 3 3 2 3 3 2]
 [3 3 1 3 1 3 2 1 2 3]
 [3 1 2 1 3 2 1 1 3 2]
 [3 2 3 3 2 1 1 1 2 3]
 [1 1 3 2 2 3 2 2 1 2]
 [2 1 3 3 3 3 1 1 1 3]]


In [20]:
d[-1]

array([2, 1, 3, 3, 3, 3, 1, 1, 1, 3])

In [21]:
d[3,5]   # d[0][0]

2

In [22]:
d[4,4]

3

In [23]:
d[:, -3]

array([1, 1, 1, 3, 3, 1, 1, 1, 2, 1])

In [24]:
d[:5, 2]   # first five rows of column idx 2

array([3, 1, 2, 3, 2])

In [25]:
d[5:, 2] # last five rows of column idx 2

array([1, 2, 3, 3, 3])

In [26]:
d[:5, :5]

array([[2, 1, 3, 3, 1],
       [1, 2, 1, 2, 3],
       [2, 3, 2, 3, 2],
       [3, 2, 3, 1, 3],
       [1, 3, 2, 1, 3]])

In [27]:
x = np.random.randint(1,10, (3,3))
y = np.random.randint(1,10, (3,3))
print(x,'\n', y)

[[9 3 5]
 [9 4 6]
 [2 3 6]] 
 [[8 8 1]
 [6 4 7]
 [4 1 4]]


In [28]:
x+y

array([[17, 11,  6],
       [15,  8, 13],
       [ 6,  4, 10]])

In [29]:
x-y

array([[ 1, -5,  4],
       [ 3,  0, -1],
       [-2,  2,  2]])

In [30]:
x*y

array([[72, 24,  5],
       [54, 16, 42],
       [ 8,  3, 24]])

In [31]:
x/y

array([[1.125     , 0.375     , 5.        ],
       [1.5       , 1.        , 0.85714286],
       [0.5       , 3.        , 1.5       ]])

In [32]:
x + 10

array([[19, 13, 15],
       [19, 14, 16],
       [12, 13, 16]])

In [33]:
x - 10

array([[-1, -7, -5],
       [-1, -6, -4],
       [-8, -7, -4]])

In [34]:
x * 10

array([[90, 30, 50],
       [90, 40, 60],
       [20, 30, 60]])

In [35]:
np.matmul(x,y)

array([[110,  89,  50],
       [120,  94,  61],
       [ 58,  34,  47]])

In [36]:
x * y

array([[72, 24,  5],
       [54, 16, 42],
       [ 8,  3, 24]])

In [37]:
np.cross(x,y)

array([[-37,  31,  48],
       [  4, -27,  12],
       [  6,  16, -10]])

In [38]:
np.hstack([x,y])

array([[9, 3, 5, 8, 8, 1],
       [9, 4, 6, 6, 4, 7],
       [2, 3, 6, 4, 1, 4]])

In [39]:
np.vstack([x,y])

array([[9, 3, 5],
       [9, 4, 6],
       [2, 3, 6],
       [8, 8, 1],
       [6, 4, 7],
       [4, 1, 4]])

In [40]:
np.append(x,y, axis = 0)  # axis 0 is for row wise and  1 for column

array([[9, 3, 5],
       [9, 4, 6],
       [2, 3, 6],
       [8, 8, 1],
       [6, 4, 7],
       [4, 1, 4]])

In [41]:
x.max()

9

In [42]:
x.max(axis = 0)

array([9, 4, 6])

In [43]:
x.min(axis = 1)

array([3, 4, 2])

In [44]:
x.flatten()

array([9, 3, 5, 9, 4, 6, 2, 3, 6])

In [45]:
d[d > 2]   # boolean filter

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [46]:
d[d == 1]     # give all the ones

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1])